INSERT INTO CUSTOMER (ID, NAME, SURNAME, CF, NDG) VALUES ('1', 'Mario', 'Zilioli', 'GCAATANNBMMENNNE', '143256');
INSERT INTO CUSTOMER (ID, NAME, SURNAME, CF, NDG) VALUES ('2', 'Luisa', 'Rossi', 'KYC1427706084003', '186584');
INSERT INTO CUSTOMER (ID, NAME, SURNAME, CF, NDG) VALUES ('3', 'Pietro', 'Brambilla', 'AATAAANNBMMENNNE', '123534');
INSERT INTO CUSTOMER (ID, NAME, SURNAME, CF, NDG) VALUES ('4', 'Mario', 'Rossi', 'AAGACANNBMMENNNE', '975334');
INSERT INTO CUSTOMER (ID, NAME, SURNAME, CF, NDG) VALUES ('5', 'Luigi', 'Rossi', 'ABAABANNBMMENNNE', '753734');
INSERT INTO CUSTOMER (ID, NAME, SURNAME, CF, NDG) VALUES ('6', 'Mario', 'Bianchi', 'AABAABNNBMMENNNE', '122462');